// <auto-generated />
namespace FlightBookingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class M8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M8));
        
        string IMigrationMetadata.Id
        {
            get { return "202412181431197_M8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
